# Generated by Django 4.1.7 on 2023-04-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_movie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='specification',
            field=models.IntegerField(choices=[(1, 'Movie'), (2, 'series'), (3, 'trailers')], default=1),
        ),
    ]
